[package]
name = "BIN-ALKEN-Convertor"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.6"
calamine = "0.25"
csv = "1.3"
rfd = "0.14"
anyhow = "1.0"

[build-dependencies]
slint-build = "1.6"